### ISSUE TITLE
[Task] Example task

### ISSUE THREAD

**Issue by Tysyatsky** [Tysyatsky/LuggageLocate#1]
## Task Details
- **Priority:** High
- **Assignee:** @Tysyatsky 
- **Due Date:** 2023-10-19
- **Story Points:** 8 

## Task Requirements
1. Do thing one;
2. Do thing two;
3. Create special feature, no bugs.

## Additional Information
Link from StachOvee: https://www.google.com/search?q=matlab+simulink+variable+input&client=opera-gx&hs=8gr&sca_esv=573847129&sxsrf=AM9HkKkrfK_700-0DS_y9x21w7eanLdd7A%3A1697482373204&ei=hYYtZZb5C_-_wPAP7NGUiA4&oq=matlab+sim+input&gs_lp=Egxnd3Mtd2l6LXNlcnAiEG1hdGxhYiBzaW0gaW5wdXQqAggCMgYQABgHGB4yBhAAGAcYHjIGEAAYBxgeMgYQABgHGB4yBhAAGAcYHjIGEAAYBxgeMgYQABgHGB4yBhAAGAcYHjIGEAAYBxgeMgYQABgHGB5IpDtQkQZY7SBwBHgBkAEAmAGqAaAB0ASqAQM1LjG4AQPIAQD4AQHCAgoQABhHGNYEGLADwgIKEAAYigUYsAMYQ8ICDBAjGIoFGBMYgAQYJ8ICCBAAGAcYHhgTwgIIECEYoAEYwwTCAggQABgeGA0YD-IDBBgAIEGIBgGQBgo&sclient=gws-wiz-serp#ip=1

## Acceptance Criteria
1. Create entity one;
2. Validate;
3. Coverage: 90%

## Tasks Checklist
- [ ] Task requirements outlined.
- [ ] Code changes implemented.
- [x] Unit tests written and passing.
- [x] Code reviewed and approved.
- [ ] Documentation updated.

added comment.

**Comment by Tysyatsky** [comment]
Small comment. Add

**Comment by Tysyatsky** [comment]
![dfe6ff10-19ca-11ee-8d5b-8f954b8ec342](https://github.com/Tysyatsky/LuggageLocate/assets/77460353/56345747-c801-498b-bd2d-7d1f70502bea)
